name: Generate Daily Math Content

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every hours a day UTC
  workflow_dispatch:      # Allows you to click a button to run it manually

permissions:
  contents: write         # Gives the robot permission to save the JSON files

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Pandas
      run: pip install pandas
      
    - name: Run Generators
      run: python generate_daily.py
      
    - name: Commit New Questions
      run: |
        git config --global user.name 'MathBot'
        git config --global user.email 'bot@noreply.github.com'
        git add hard_questions.json expert_questions.json
        git commit -m "Fresh Daily Content Generated" || echo "No changes to commit"
        git push
